name: Main Workflow
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - run: echo Build
  test:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - run: echo Build
  package:
    needs: test
    runs-on: ubuntu-latest
    steps:
    - run: echo Build
  deploy:
    needs: package
    runs-on: ubuntu-latest
    steps:
    - run: echo Build
